---
apiVersion: v1
kind: Secret
metadata:
  name: ryanj3-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/ryanj3-frontend-gitops
